{% set name = "thuner" %}
{% set version = "0.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: <sha256-checksum>

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - thuner

about:
  home: https://github.com/THUNER-project/THUNER
  license: BSD-3-Clause
  summary: "The Thunderstorm Event Reconnaissance (THUNER) package is a toolkit for tracking and analyzing meteorological events, primarily convective events."

extra:
  recipe-maintainers:
    - eshort0401