{% set name = "thuner" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thuner-{{ version }}.tar.gz
  sha256: 181c9481ea5209e9237be6d9146d86da8260a2ed0aef4674137c2f7f15095491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy
    - numba
    - scipy
    - scikit-image
    - pandas
    - matplotlib-base
    - xarray
    - cartopy
    - typing_extensions
    - pre-commit
    - black
    - pytest
    - pytest-cov
    - codecov
    - ipykernel
    - netcdf4
    - h5netcdf
    - requests
    - arm_pyart
    - tqdm
    - cdsapi
    - xesmf
    - opencv
    - pytables
    - pydantic
    - zarr
    - windrose
    - pydot
    - python-graphviz
    - metpy
    - nbconvert

test:
  imports:
    - thuner
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Multifeature tracking and analysis of meteorological events
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - eshort0401
