@startuml packages
set namespaceSeparator none
package "thuner" as thuner {
}
package "thuner.analyze" as thuner.analyze {
}
package "thuner.attribute" as thuner.attribute {
}
package "thuner.data" as thuner.data {
}
package "thuner.default" as thuner.default {
}
package "thuner.detect" as thuner.detect {
}
package "thuner.grid" as thuner.grid {
}
package "thuner.group" as thuner.group {
}
package "thuner.match" as thuner.match {
}
package "thuner.option" as thuner.option {
}
package "thuner.parallel" as thuner.parallel {
}
package "thuner.track" as thuner.track {
}
package "thuner.visualize" as thuner.visualize {
}
package "thuner.write" as thuner.write {
}
thuner --> thuner.analyze
thuner --> thuner.data
thuner --> thuner.default
thuner --> thuner.option
thuner --> thuner.parallel
thuner --> thuner.track
thuner --> thuner.visualize
thuner.analyze --> thuner.attribute
thuner.analyze --> thuner.option
thuner.analyze --> thuner.write
thuner.attribute --> thuner.option
thuner.attribute --> thuner.grid
thuner.attribute --> thuner.match
thuner.data --> thuner.grid
thuner.default --> thuner.attribute
thuner.default --> thuner.option
thuner.default --> thuner.visualize
thuner.match --> thuner.grid
thuner.option --> thuner.data
thuner.parallel --> thuner.analyze
thuner.parallel --> thuner.attribute
thuner.parallel --> thuner.data
thuner.parallel --> thuner.option
thuner.parallel --> thuner.track
thuner.parallel --> thuner.write
thuner.track --> thuner.attribute
thuner.track --> thuner.data
thuner.track --> thuner.detect
thuner.track --> thuner.group
thuner.track --> thuner.match
thuner.track --> thuner.option
thuner.track --> thuner.visualize
thuner.track --> thuner.write
thuner.visualize --> thuner.analyze
thuner.visualize --> thuner.attribute
thuner.visualize --> thuner.data
thuner.visualize --> thuner.detect
thuner.visualize --> thuner.grid
thuner.visualize --> thuner.match
thuner.write --> thuner.attribute
thuner.write --> thuner.option
@enduml
