name: THUNER
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sphinx
  - sphinx-rtd-theme
  - autodoc_pydantic
  - numpy=2.0
  - numba=0.60
  - scipy=1.14
  - scikit-image=0.24
  - pandas=2.2
  - matplotlib=3.9
  - xarray=2024.9
  - cartopy=0.24
  - typing_extensions=4.12
  - codecov=2.1
  - ipykernel=6.29
  - netcdf4=1.7
  - h5netcdf=1.4
  - requests=2.32
  - arm_pyart=1.19
  - tqdm=4.66
  - cdsapi=0.7
  - xesmf=0.8
  - opencv=4.10
  - nco=5.2
  - pytables=3.10
  - pydantic=2.9
  - zarr=2.18
  - windrose=1.9
  - pydot=3.0
  - metpy=1.6
  - graphviz=12.2
  - pygraphviz=1.14
  - nbconvert=7.16