name: THUNER_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - numpy
  - autodoc-pydantic
  - pydantic
  - ipykernel
  - xarray
  - pandas
  - matplotlib
  - arm_pyart>=1.19,<2
  - pyarrow
  - dask